
spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html

springdoc:
  swagger-ui:
    path: /swagger-ui.html


