
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates
    suffix: .html

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



jwt:
  securityKey: qwertyuiop1234567yuitrewwwdfgbhjklkmjnzsd567890hgjdfgtreyuhnbvfgsssjkj8765432rtwuh


