spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://192.168.1.100:3306/salary_disbursements_platform?createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Africa/Harare&allowPublicKeyRetrieval=true
    username: 'root'
    password: 'skdcnwauicn2ucnaecasdsajdnizucawencascdca'
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      maximum-pool-size: 3
      initialization-mode: always
    jpa:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      database: MYSQL
      show-sql: true
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update

      properties:
        hibernate.id.new_generator_mappings: true
        hibernate.connection.provider_disables_autocommit: true
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
        hibernate.jdbc.batch_size: 500
        hibernate.order_inserts: true
        hibernate.order_updates: true
        hibernate.query.fail_on_pagination_over_collection_fetch: true
        hibernate.query.in_clause_parameter_padding: true
      data:
        jpa:
          repositories:
            bootstrap-mode: lazy

      jackson:
        serialization:
          fail-on-empty-beans: false

storage:
  uploads:
    files: uploads/files/