version: '3'
services:
  traefik:
    image: traefik:v2.0.2
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    labels:
      - "traefik.http.routers.traefik.rule=Host('localhost.com')"
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/log:/var/log
    networks:
      platform-network:
        ipv4_address: "192.168.1.200"

  salarymanager:
    depends_on:
      - maria-test-db
    container_name: salarymanager
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: wibzin/salary_manager:v1
    ports:
      - 8080:8080
    volumes:
    - /home/all_uploads:/app/uploads/files
    - /home/remittance:/app/uploads/remittance
    #volumes:
    #  - ~/home/administrator/ssk:/app


    #volumes:
    #  - /home/administrator/requests:/home/administrator/requests


    networks:
      platform-network:
        ipv4_address: "192.168.1.101"

  maria-test-db:
    image: bitnami/mariadb:latest
    container_name: salarymanagertestdb
    ports:
      - 3303:3306
    environment:
      - "MARIADB_ROOT_PASSWORD=skdcnwauicn2ucnaecasdsajdnizucawencascdca"
      - "MARIADB_USER=developer"
      - "MARIADB_PASSWORD=#m3tb@nk1#"
      - "MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=300"
      - "MARIADB_DATABASE=test_database"
    restart: on-failure
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      platform-network:
        ipv4_address: "192.168.1.100"




networks:
  platform-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24


volumes:
  mariadb-data:
    driver: local
  #file-uploads:
   # driver: local